### ISSUE TITLE
Auto-provided JDK does not work with Mac OS ARM

### ISSUE THREAD

**Issue by szymon-owczarzak** [wttech/aemc#209]
Hi, I was just testing AEMC and I'm very impressed ! Great work @krystian-panek-wttech .

However I found a minor bug in your config:
On my MacBook Pro with `Apple M1` chip running `Mac OS Ventura 13.6.1` auto provided JDK does not work.

```
ERRO[2023-10-26 15:52:32] cannot check java version properly: '': fork/exec /Users/xxx/IdeaProjects/xxx-aem/aem/home/opt/java/jdk/jdk-11.0.18+10/Contents/Home/bin/java: bad CPU type in executable 
task: Failed to run task "aem:setup": exit status 1
```

changing this options:
```
      # enforce non-ARM Java as some AEM features are not working on ARM (e.g Scene7)
      "arm64": "x64"
      "aarch64": "x64"
```
to
```
      # enforce non-ARM Java as some AEM features are not working on ARM (e.g Scene7)
      "arm64": "aarch64"
      "aarch64": "aarch64"
```
fixes the issue.

**Comment by krystian-panek-wttech** [comment]
Thanks for the feedback. 

It is intentional because as stated in comment AEM is not officially working on AEM. Moreover scene7 as far as I know does not work at all... That's why I am forcing to install non-arm java I on arm. It works but you then need to have rosetta installed on your mac. And that part is missing here. I just haven't documented that. I will document it thanks.
