### ISSUE TITLE
AEM dispatcher integration

### ISSUE THREAD

**Issue by krystian-panek-wttech** [wttech/aemc#27]
- check if unpacked SDK docker image is usable (using #11)
- try to use SDK dispatcher tools as is
- consider using aem-ethos in docker-compose

**Comment by krystian-panek-wttech** [comment]
@tomasz-sobczyk-wttech 

I am opting this time for using AEM dispatcher tools from SDK as is (without docker-compose). to be more aligned and familiar with Adobe tools.

WDYT?

**Comment by maciej-majchrzak-wttech** [comment]
I think this is fine as long as there's nothing in aemc which prevents different setup, i.e. on-prem setup without SDK and with custom docker image for dispatcher

**Comment by krystian-panek-wttech** [comment]
project initialized for cloud AEM now has nicely integrated AEM dispatcher ethos deployed via docker-compose:

https://github.com/wttech/aemc/blob/main/project/cloud/docker-compose.yml#L4
https://github.com/wttech/aemc/blob/main/project/cloud/aem/script/deploy.sh#L20

now working on at first building then deploying dispatcher image for on-prem to handle dispatcher.ams config from archetype

**Comment by krystian-panek-wttech** [comment]
done; depending on how project is initialized `aemw project init --kind [classic|cloud]` then for

- cloud - SDK/aem-ethos dispatcher image is used as is and dispatcher/src files are mounted via volume
- classic - custom image based on rocky linux is built, dispatcher/src are put into container during docker build stage; the intention here is that built image should work/pretend as AMS dispatcher using RHEL; some of AMS-specific configs are mitigates/workarounded as they are causing some problems when launching  dispatcher on docker/locally

**Comment by royteeuwen** [comment]
@krystian-panek-wttech is there a big difference between the AMS and the Cloud one in layout of files / functionality? Did you consider using the cloud sdk one for on prem situations? 

I'm doubting on what approach to take, wanting to keep it as simple and as aligned between local and the higher envs, and having an easy migration to cloud if it would ever come ;)

**Comment by krystian-panek-wttech** [comment]
You know, the fewer differences you have on your runtimes the more confident you could be when going from local to higher envs 🙂 I am just keeping reflecting the same setup that I am observing on AMS and I believe it's a good approach - no issues spotted so far in day-to-day work.

If you need config mgmt yep Ansible is the only choice but after playing with it more it's also problematic (python versions hell is there, os-specific glitches etc.). Instead now I prefer to use IaaC for example https://github.com/wttech/terraform-provider-aem and limit config mgmt to only radically simple bash scripts with idempotence. Ultimately this approach could eliminate config mgmt at all and all pieces in the infrastructure should be then manageable via TF or Pulumi which is a much more easy thing to do.

If you will use Ansible and some module will be missing, I mean tiny wrapper on the top of AEM CLI I could supplement it for you or don't hesitate to create PR 🙂

**Comment by royteeuwen** [comment]
And do you also deploy on the higher envs the dispatcher as a separate docker container or maybe even a kubernetes pod :)? That's a part I'm still doubting about, currently the dispatcher is on the same vm as AEM itself, with it's benefits and drawbacks.

Well, so far I think we will be going for Ansible, because we have on-premises datacenters, no AWS / Azure / ... (and we can't change that). I haven't used / seen Terraform yet if it even works in on-premises datacenters. 

And of course, if I have anything that can be contributed, I'll make sure we will always do! I'm making a list of all the features in Puppet that we use for AEM and Dispatcher and then as second phase I'll make the comparison with what aem compose provides and OOTB ansible / community modules. Hopefully it'l match for most of it.

**Comment by krystian-panek-wttech** [comment]
These AEM ansible modules are already in use for some clients.. So they are already 'warmed up' and nobody reported to me issues fortunately 🙂  so I hope you will not experience issues as well. regarding 'where to deploy dispatcher container' , yep ECS feels natural (EKS maybe for more complex architectures for better scaling), but if you could only use VMS, maybe just install httpd on the very tiny separate machine and deploy the dispatcher zip config there. Since you are still on prem you could forget about containers? Aren't you? 😉

**Comment by royteeuwen** [comment]
Good to hear that they are production ready 😄! 

We have a managed Kubernetes on-premises, so it's definitely possible ;), it's just not reachable from Ansible because it's a totally different platform, so to be determined if that's something we want.
 
In any case, I'll figure something out, thanks for the help so far!
